version: '3.2'

services:
  api:
    image: 298618414706.dkr.ecr.ap-northeast-1.amazonaws.com/checkcalorie-api:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 23000:3000
    depends_on:
      - database
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 28000:3000
  database:
    restart: always
    image: mysql:5.7.32
    platform: linux/x86_64
    ports:
      - 23306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-datavolume:
    driver: local